/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LanguageSelect: typeof import('./src/components/LanguageSelect.vue')['default']
    LeftMessage: typeof import('./src/components/Conversation/LeftMessage.vue')['default']
    ModelSelect: typeof import('./src/components/ModelSelect.vue')['default']
    RightMessage: typeof import('./src/components/Conversation/RightMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
